title: FCE English Lab
description: Preparación práctica para Cambridge B2 First
url: "https://jnfz92.github.io"
baseurl: ""
lang: es
permalink: /articles/:categories/:title/
paginate: 6
paginate_path: "/page/:num/"
plugins:
  - jekyll-paginate
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: jnf92
